version: '3.7'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: memorial
      POSTGRES_PASSWORD: memorialPassword
      POSTGRES_DB: memorial
    ports:
      - "5432:5432"
    volumes:
      - "./data_dir:/var/lib/postgresql/data"